### ISSUE TITLE
Get Cody to get a Github account

### ISSUE THREAD

**Issue by mikehmbn** [WSU-Vancouver-IEEE-Club/cougballoon2.0#3]
And check out the code he did yesterday and compare to what you did. Post it to git.

**Comment by emanuelbrici** [comment]
What is Cody's username for github? Or does he not have one at all?

**Comment by mikehmbn** [comment]
he doesn't have one. I did that as a test for my github knowledge also, 
just an excuse to click buttons on it.

**Comment by mikehmbn** [comment]
He doesn't have an account (yet).

**Comment by emanuelbrici** [comment]
Okay good to know. What code was he working on yesterday?

**Comment by mikehmbn** [comment]
Satellite transmitter.

**Comment by emanuelbrici** [comment]
Just testing this out to see how it appears on github when replying from email.
On Feb 21, 2016, at 7:28 PM, Michael Hamilton <notifications@github.com<mailto:notifications@github.com>> wrote:

Satellite transmitter.

**Comment by mikehmbn** [comment]
boom.

**Comment by emanuelbrici** [comment]
Nice. Good to know how that works.
